apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app-name-here
  description: "Your app description here"
  # links:
  #   - url:
  #     title: 'Your app name here'
  #     icon: dashboard
  tags:
    - nestjs
    - typescript
  annotations:
    sonarqube.org/project-key: app-name-here
spec:
  type: service
  lifecycle: production
  owner: desenvolvedores
  system: autorizador
  dependsOn:
    - resource:app-name-here-api-db
  providesApis:
    - app-name-here-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: app-name-here-api-db
  description: "Your app name here database"
  tags:
    - postgres
spec:
  type: database
  owner: dbas
  system: autorizador
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: app-name-here-api
  description: GraphQL API.
spec:
  type: graphql
  lifecycle: production
  owner: desenvolvedores
  definition: "type Query { toDo: String }"
