apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: habita
  description: |
    API GraphQL do sistema imobiliário Habita
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - template
    - typescript
    - javascript
    - nestjs

spec:
  type: service
  owner: desenvolvedores
  lifecycle: production
  system: suporte-desenvolvedores
