sonar.projectKey=app-name-here
sonar.qualitygate.wait=true
sonar.sources=src
sonar.exclusions=**\*spec.ts,**\*spec.js,src/migrations,test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=config/**,coverage/**,docs/**,locales/**,bin/**,logs/**,tests/**,src/config/**,node_modules/**,src/**/*.spec.ts,src/**/*.spec.js,test,commitizen.config.js,changelog.config.js
